# Generated by Django 5.2.7 on 2025-10-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type_room',
            field=models.CharField(choices=[('standart', 'Standart'), ('lux', 'Lux'), ('suite', 'Suite'), ('family', 'Family'), ('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('deluxe', 'Deluxe'), ('presidential', 'Presidential'), ('penthouse', 'Penthouse'), ('cottage', 'Cottage'), ('villa', 'Villa'), ('bungalow', 'Bungalow'), ('hostel', 'Hostel'), ('dormitory', 'Dormitory'), ('capsule', 'Capsule'), ('igloo', 'Igloo'), ('treehouse', 'Treehouse'), ('yurt', 'Yurt'), ('cabin', 'Cabin'), ('chalet', 'Chalet'), ('farmstay', 'Farmstay'), ('glamping', 'Glamping'), ('ryokan', 'Ryokan'), ('pousada', 'Pousada'), ('parador', 'Parador'), ('auberge', 'Auberge'), ('hostal', 'Hostal'), ('motel', 'Motel'), ('inn', 'Inn'), ('guesthouse', 'Guesthouse')], default='standart', max_length=100),
        ),
    ]
